export const SCREENS = {
  entry: {
    id: "entry",
    type: "text",
    lines: ["Kamu tidak tersesat.", "Kamu hanya berhenti sebentar.", ""],
    choices: null,
    next: "s01",
  },
  s01: {
    id: "s01",
    type: "text",
    lines: [
      "Aku sudah melihatmu cukup lama.",
      "Aku tahu caramu diam dan pura-pura.",
      "Tenang. Aku tidak datang untuk menilai.",
    ],
    choices: null,
    next: "s02",
  },
  s02: {
    id: "s02",
    type: "choice",
    lines: [
      "Kalau orang lain melihatmu hari ini,",
      "mereka mungkin akan bilang kamu…",
      "",
    ],
    choices: [
      { label: "terlihat baik-baik saja", next: "s03a" },
      { label: "terlihat sibuk dan kuat", next: "s03b" },
      { label: "terlihat tenang, meski kosong", next: "s03c" },
      { label: "tidak ada yang benar-benar melihat", next: "s03d" },
    ],
    next: null,
  },
  s03a: {
    id: "s03a",
    type: "text",
    lines: [
      "Baik-baik saja adalah kata yang paling lelah.",
      "Aku tahu berapa energi yang kamu habiskan.",
      "Untuk menjaga kata itu tetap berdiri.",
    ],
    choices: null,
    next: "s04a",
  },
  s03b: {
    id: "s03b",
    type: "text",
    lines: [
      "Sibuk bisa menjadi cara paling halus untuk bersembunyi.",
      "Aku menonton kamu berlari dari satu hal ke hal lain.",
      "Dan tidak pernah berhenti untuk bertanya pada diri sendiri.",
    ],
    choices: null,
    next: "s04b",
  },
  s03c: {
    id: "s03c",
    type: "text",
    lines: [
      "Tenang yang kosong adalah yang paling berat.",
      "Orang mengira itu kedamaian padahal itu lelah.",
      "Aku tahu kamu tahu perbedaannya.",
    ],
    choices: null,
    next: "s04c",
  },
  s03d: {
    id: "s03d",
    type: "text",
    lines: [
      "Tidak dilihat adalah rasa yang paling biasa.",
      "Bukan karena kamu tidak ada di sana.",
      "Tapi karena kamu tidak pernah mengambil tempat.",
    ],
    choices: null,
    next: "s04d",
  },
  s04a: {
    id: "s04a",
    type: "choice",
    lines: [
      "Tapi di balik semua itu, kamu lebih sering merasa…",
      "Hal yang tidak kamu bawa keluar rumah.",
      "",
    ],
    choices: [
      { label: "lelah tanpa sebab yang jelas", next: "s05a" },
      { label: "sedih tanpa cerita yang rapi", next: "s05b" },
      { label: "marah pada diri sendiri", next: "s05c" },
      { label: "rindu pada sesuatu yang tidak bisa disebut", next: "s05d" },
    ],
    next: null,
  },
  s04b: {
    id: "s04b",
    type: "choice",
    lines: [
      "Di celah-celah kesibukanmu, ada yang menunggu.",
      "Perasaan yang tidak pernah dapat giliran bicara.",
      "",
    ],
    choices: [
      { label: "lelah tanpa sebab yang jelas", next: "s05a" },
      { label: "sedih tanpa cerita yang rapi", next: "s05b" },
      { label: "marah pada diri sendiri", next: "s05c" },
      { label: "rindu pada sesuatu yang tidak bisa disebut", next: "s05d" },
    ],
    next: null,
  },
  s04c: {
    id: "s04c",
    type: "choice",
    lines: [
      "Di balik ketenangan itu, ada sesuatu yang menggerak.",
      "Sangat pelan, sangat sunyi, tapi ada.",
      "",
    ],
    choices: [
      { label: "lelah tanpa sebab yang jelas", next: "s05a" },
      { label: "sedih tanpa cerita yang rapi", next: "s05b" },
      { label: "marah pada diri sendiri", next: "s05c" },
      { label: "rindu pada sesuatu yang tidak bisa disebut", next: "s05d" },
    ],
    next: null,
  },
  s04d: {
    id: "s04d",
    type: "choice",
    lines: [
      "Justru karena tidak ada yang melihat, kamu bebas.",
      "Untuk mengakui hal yang paling tersembunyi.",
      "",
    ],
    choices: [
      { label: "lelah tanpa sebab yang jelas", next: "s05a" },
      { label: "sedih tanpa cerita yang rapi", next: "s05b" },
      { label: "marah pada diri sendiri", next: "s05c" },
      { label: "rindu pada sesuatu yang tidak bisa disebut", next: "s05d" },
    ],
    next: null,
  },
  s05a: {
    id: "s05a",
    type: "text",
    lines: [
      "Lelah yang tidak punya nama adalah yang paling berat.",
      "Bukan karena tidak ada alasan.",
      "Tapi karena alasannya terlalu banyak untuk dihitung.",
    ],
    choices: null,
    next: "s06a",
  },
  s05b: {
    id: "s05b",
    type: "text",
    lines: [
      "Sedih yang tidak rapi adalah sedih yang paling jujur.",
      "Tidak perlu cerita untuk membenarkannya.",
      "Ia ada, dan itu cukup untuk mengakuinya.",
    ],
    choices: null,
    next: "s06b",
  },
  s05c: {
    id: "s05c",
    type: "text",
    lines: [
      "Marah pada diri sendiri biasanya bukan tentang kesalahan.",
      "Tapi tentang semua hal yang kamu rasa seharusnya.",
      "Dan tidak pernah menjadi seperti yang kamu bayangkan.",
    ],
    choices: null,
    next: "s06c",
  },
  s05d: {
    id: "s05d",
    type: "text",
    lines: [
      "Rindu yang tidak punya alamat adalah yang paling aneh.",
      "Bukan tentang seseorang yang pergi.",
      "Tapi tentang versi hidupmu yang tidak pernah datang.",
    ],
    choices: null,
    next: "s06d",
  },
  s06a: {
    id: "s06a",
    type: "text",
    lines: [
      "Kamu mungkin mengira ini tentang orang tertentu.",
      "Tapi kelelahan ini terlalu besar untuk satu nama.",
      "Ia datang dari tempat yang lebih dalam dari itu.",
    ],
    choices: null,
    next: "__DYNAMIC_S07__",
  },
  s06b: {
    id: "s06b",
    type: "text",
    lines: [
      "Banyak orang akan mengira kamu sedih karena seseorang.",
      "Tapi kesedihan ini lebih tua dari siapa pun.",
      "Ia sudah ada sebelum kamu mengenal nama apa pun.",
    ],
    choices: null,
    next: "__DYNAMIC_S07__",
  },
  s06c: {
    id: "s06c",
    type: "text",
    lines: [
      "Orang sering mengira kemarahan ini punya target.",
      "Tapi ini bukan tentang siapa yang mengecewakan.",
      "Ini tentang jarak antara kamu dan bayangan dirimu.",
    ],
    choices: null,
    next: "__DYNAMIC_S07__",
  },
  s06d: {
    id: "s06d",
    type: "text",
    lines: [
      "Orang mengira kerinduan ini punya wajah.",
      "Tapi yang kamu rindukan bukan seseorang.",
      "Ia adalah versi dari hidupmu yang terus berjalan tanpamu.",
    ],
    choices: null,
    next: "__DYNAMIC_S07__",
  },
  s07_aa: {
    id: "s07_aa",
    type: "text",
    lines: [
      "Seperti rumah yang selalu rapi tapi lampunya tidak pernah menyala.",
      "Semuanya di tempat yang benar.",
      "Tapi ada sesuatu yang sudah pergi dari dalamnya.",
    ],
    choices: null,
    next: "s08",
  },
  s07_ab: {
    id: "s07_ab",
    type: "text",
    lines: [
      "Seperti surat yang sudah dikirim tapi tidak pernah tiba.",
      "Kata-katanya masih ada di dalam amplop.",
      "Tapi tangan yang menulis sudah melanjutkan hidupnya.",
    ],
    choices: null,
    next: "s08",
  },
  s07_ac: {
    id: "s07_ac",
    type: "text",
    lines: [
      "Seperti cermin yang dipasang sempurna tapi kamu tidak berani mendekati.",
      "Bayangan di sana masih ada.",
      "Dan ia menunggu kamu dengan sabar.",
    ],
    choices: null,
    next: "s08",
  },
  s07_ad: {
    id: "s07_ad",
    type: "text",
    lines: [
      "Seperti jalan yang sudah kamu hafal tapi kamu lewati terlalu cepat.",
      "Setiap tikungannya masih ada.",
      "Tapi kamu tidak pernah berhenti untuk duduk di sana.",
    ],
    choices: null,
    next: "s08",
  },
  s07_ba: {
    id: "s07_ba",
    type: "text",
    lines: [
      "Seperti mesin yang terus berjalan malam dan siang.",
      "Suaranya mengisi seluruh ruangan.",
      "Tapi tidak ada yang mendengar apa yang ia minta.",
    ],
    choices: null,
    next: "s08",
  },
  s07_bb: {
    id: "s07_bb",
    type: "text",
    lines: [
      "Seperti musik yang dimainkan di ruangan kosong.",
      "Nadanya sempurna dan tidak ada yang mendengarkan.",
      "Dan pemainnya tidak tahu kapan ia bisa berhenti.",
    ],
    choices: null,
    next: "s08",
  },
  s07_bc: {
    id: "s07_bc",
    type: "text",
    lines: [
      "Seperti anak tangga yang selalu kamu naiki.",
      "Kamu sampai di atasnya dan tidak ada yang menunggu.",
      "Hanya udara dan pertanyaan yang sama.",
    ],
    choices: null,
    next: "s08",
  },
  s07_bd: {
    id: "s07_bd",
    type: "text",
    lines: [
      "Seperti kereta yang selalu tepat jadwal tapi tidak pernah berhenti.",
      "Kamu menonton platform berlalu dari jendela.",
      "Dan satu di antaranya harusnya menjadi milikmu.",
    ],
    choices: null,
    next: "s08",
  },
  s07_ca: {
    id: "s07_ca",
    type: "text",
    lines: [
      "Seperti danau yang permukaannya sempurna tenang.",
      "Tidak ada yang tahu berapa dalamnya di bawah sana.",
      "Dan air itu tidak pernah naik untuk memberitahu.",
    ],
    choices: null,
    next: "s08",
  },
  s07_cb: {
    id: "s07_cb",
    type: "text",
    lines: [
      "Seperti hujan yang turun di malam yang sudah gelap.",
      "Tidak ada yang melihat tapi tanahnya tetap basah.",
      "Dan di pagi hari semua orang bilang cuacanya bagus.",
    ],
    choices: null,
    next: "s08",
  },
  s07_cc: {
    id: "s07_cc",
    type: "text",
    lines: [
      "Seperti taman yang terlihat indah dari luar pagar.",
      "Tapi di dalamnya ada pohon yang sudah lama kering.",
      "Dan tidak ada yang masuk untuk menyiram.",
    ],
    choices: null,
    next: "s08",
  },
  s07_cd: {
    id: "s07_cd",
    type: "text",
    lines: [
      "Seperti pantai di pagi hari yang sangat sunyi.",
      "Ombaknya masih datang dan pergi seperti biasanya.",
      "Tapi jejak kakimu dari kemarin sudah dihapus.",
    ],
    choices: null,
    next: "s08",
  },
  s07_da: {
    id: "s07_da",
    type: "text",
    lines: [
      "Seperti lampu di lorong yang tidak pernah ada fotonya.",
      "Ia menyala setiap malam tanpa siapa pun tahu.",
      "Dan terobosan yang ia berikan tidak pernah dicatat.",
    ],
    choices: null,
    next: "s08",
  },
  s07_db: {
    id: "s07_db",
    type: "text",
    lines: [
      "Seperti halaman buku yang tidak pernah dibaca sampai habis.",
      "Kata-katanya masih ada di sana setiap kali buku itu dibuka.",
      "Tapi tidak ada yang tahu cerita apa yang menunggu.",
    ],
    choices: null,
    next: "s08",
  },
  s07_dc: {
    id: "s07_dc",
    type: "text",
    lines: [
      "Seperti bayangan yang selalu ikut tapi tidak pernah disapa.",
      "Ia ada di samping kamu setiap hari.",
      "Dan ia mulai capek menunggu untuk diakui.",
    ],
    choices: null,
    next: "s08",
  },
  s07_dd: {
    id: "s07_dd",
    type: "text",
    lines: [
      "Seperti pintu yang selalu terbuka tapi tidak ada yang masuk.",
      "Anginnya masih terasa dari dalam ruangan.",
      "Tapi tidak ada suara yang menyebut nama tempat itu.",
    ],
    choices: null,
    next: "s08",
  },
  s08: {
    id: "s08",
    type: "text",
    lines: [
      "Kamu sering berpikir seharusnya kamu sudah di tempat lain.",
      "Tempat di mana semuanya terasa lebih pasti dan pantas.",
      "Tempat yang terasa lebih benar dari di sini.",
    ],
    choices: null,
    next: "s09",
  },
  s09: {
    id: "s09",
    type: "choice",
    lines: [
      "Tapi kamu ada di sini.",
      "Dan yang paling melelahkan bukan posisimu.",
      "Tapi perbandingan dengan hidup yang tidak pernah terjadi.",
    ],
    choices: [
      { label: "aku tahu, dan aku sudah capek membandingkan", next: "s10a" },
      { label: "aku tidak tahu kapan aku mulai melakukan itu", next: "s10b" },
      { label: "aku masih mencoba berhenti melakukannya", next: "s10c" },
      { label: "aku tidak yakin itu yang aku rasakan", next: "s10d" },
    ],
    next: null,
  },
  s10a: {
    id: "s10a",
    type: "text",
    lines: [
      "Lelah dari perbandingan adalah langkah pertama yang nyata.",
      "Bukan berarti kamu sudah sampai di mana pun.",
      "Tapi kamu mulai berhenti mengukur dari garis yang salah.",
    ],
    choices: null,
    next: "s11",
  },
  s10b: {
    id: "s10b",
    type: "text",
    lines: [
      "Tidak tahu kapan dimulai adalah cara paling jujur untuk mengakui.",
      "Karena ia tidak masuk dengan pintu yang terlihat.",
      "Ia masuk perlahan, dari celah-celah hari yang biasa.",
    ],
    choices: null,
    next: "s11",
  },
  s10c: {
    id: "s10c",
    type: "text",
    lines: [
      "Mencoba berhenti pun adalah bentuk kesadaran.",
      "Kamu sudah tahu sesuatu yang bergerak di dalam.",
      "Dan mengakuinya adalah yang paling susah dari semuanya.",
    ],
    choices: null,
    next: "s11",
  },
  s10d: {
    id: "s10d",
    type: "text",
    lines: [
      "Tidak yakin pun boleh.",
      "Kamu tidak harus mengerti semuanya malam ini.",
      "Cukup kamu ada di sini dan jujur dengan ketidaktahuannya.",
    ],
    choices: null,
    next: "s11",
  },
  s11: {
    id: "s11",
    type: "text",
    lines: [
      "Dari tadi kamu mengira aku berbicara tentang hidupmu.",
      "Padahal, aku berbicara dari dalamnya.",
      "Aku tidak menunggumu di depan. Aku berjalan di sampingmu.",
    ],
    choices: null,
    next: "s12",
  },
  s12: {
    id: "s12",
    type: "reveal",
    lines: [
      "Aku bukan kenangan. Aku bukan orang. Aku bukan perasaan.",
      "Aku adalah bagian hidupmu yang terus berjalan.",
      "Bahkan saat kamu berhenti percaya pada diri sendiri.",
    ],
    choices: null,
    next: "s13",
  },
  s13: {
    id: "s13",
    type: "end",
    lines: [
      "Kamu tidak kehilangan apa-apa malam ini.",
      "Kamu hanya menyadari bahwa aku selalu ada.",
      "Dan meski hidup terasa berat, kamu tetap menjalaninya.",
    ],
    choices: null,
    next: "end",
  },
  end: {
    id: "end",
    type: "end",
    lines: ["Kamu boleh kembali kapan pun.", "Aku tidak ke mana-mana.", ""],
    choices: null,
    next: null,
  },
};

export const SHADOW_KEY_MAP = { s05a: "a", s05b: "b", s05c: "c", s05d: "d" };
export const PERSONA_KEY_MAP = { s03a: "a", s03b: "b", s03c: "c", s03d: "d" };
